{
 "title": "SUSE Manager Server",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "server",
    "query": "label_values(up{job='suma-server'} , instance)"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Hardware", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cores",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(node_cpu{instance=~\"$server:.*\",  mode=\"system\"} or node_cpu_seconds_total{instance=~\"$server:.*\",  mode=\"system\"})"
    }
   ]
  },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(up{instance=~\"$server:9100\"})"
    }
   ]
  },
  {
   "title": "System Load ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percentunit", "label": "load" }
   ],
   "targets": [
    {
     "expr": "(node_load1{instance=~\"$server:.*\"}) / scalar( count by (instance) (node_cpu_seconds_total{instance=~\"$server:.*\", mode=\"system\"} or node_cpu{instance=~\"$server:.*\", mode=\"system\"}))",
     "legendFormat": "load1"
    },
    {
     "expr": "(node_load5{instance=~\"$server:.*\"}) / scalar( count by (instance) (node_cpu_seconds_total{instance=~\"$server:.*\", mode=\"system\"} or node_cpu{instance=~\"$server:.*\", mode=\"system\"}))",
     "legendFormat": "load5"
    },
    {
     "expr": "(node_load15{instance=~\"$server:.*\"}) / scalar( count by (instance) (node_cpu_seconds_total{instance=~\"$server:.*\", mode=\"system\"} or node_cpu{instance=~\"$server:.*\", mode=\"system\"}))",
     "legendFormat": "load15"
    }
   ]
  },
  {
   "title": "Ram",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "node_memory_MemTotal{instance=~\"$server:.*\"} or node_memory_MemTotal_bytes{instance=~\"$server:.*\"}"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 3 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=~\"$server:.*\", mode!=\"idle\"}[5m])) / count(node_cpu_seconds_total{instance=~\"$server:.*\",  mode=\"system\"})"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(max by (device) (node_filesystem_size{instance=~\"$server:.*\", fstype=~\"vfat|btrfs|xfs|ext\\\\d\"} or node_filesystem_size_bytes{instance=~\"$server:.*\", fstype=~\"vfat|btrfs|xfs|ext\\\\d\"}))"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - ((node_memory_MemAvailable{instance=~\"$server:.*\"} / node_memory_MemTotal) or (node_memory_MemAvailable_bytes{instance=~\"$server:.*\"}) / node_memory_MemTotal_bytes)",
     "legendFormat": "RAM"
    },
    {
     "expr": "node_memory_SwapTotal_bytes{instance=~\"$server:.*\"} - node_memory_SwapFree_bytes{instance=~\"$server:.*\"}",
     "legendFormat": "swap"
    }
   ]
  },
  {
   "title": "Disk space usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "label_replace(1 - node_filesystem_avail_bytes{instance=~\"$server:.*\", fstype=~\"vfat|btrfs|xfs|ext\\\\d\"} / node_filesystem_size_bytes, \"shortdev\", \"$1\", \"device\", \"/dev/(.*)\")   ",
     "legendFormat": "{{shortdev}}"
    }
   ]
  },
  {
   "title": "mount points",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=~\"$server:.*\"}+0"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$server:.*\"}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{job=\"suma-server\",mode=\"user\"}[1m]))",
     "legendFormat": "user"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{job=\"suma-server\",mode=\"system\"}[1m]))",
     "legendFormat": "system"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{job=\"suma-server\",mode!~\"user|system|idle\"}[1m]))",
     "legendFormat": "other"
    }
   ]
  },
  {
   "title": "CPU Saturation (Runnable Processes)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_procs_running{job=\"suma-server\"}",
     "legendFormat": "running"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"$server:.*\", device=\"eth0\"}[1m])",
     "legendFormat": "in"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"$server:.*\", device=\"eth0\"}[1m])",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "Network Saturation (FIFO buffer errors)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_network_transmit_fifo_total{job=\"suma-server\",device=\"eth0\"}",
     "legendFormat": "transmit errors"
    },
    {
     "expr": "node_network_receive_fifo_total{job=\"suma-server\",device=\"eth0\"}",
     "legendFormat": "receive errors"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_disk_read_bytes_total{instance=~\"$server:.*\"}[5m]))",
     "legendFormat": "disk-read"
    },
    {
     "expr": "avg(irate(node_disk_written_bytes_total{instance=~\"$server:.*\"}[5m]))",
     "legendFormat": "disk-write"
    }
   ]
  },
  {
   "title": "Disk I/O Saturation (I/O average queue length)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_weighted_seconds_total{job=\"suma-server\", device=~\"sda|vda|xvda\"}[30s])/1000",
     "legendFormat": "length"
    }
   ]
  },
  { "title": "SUSE Manager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "JVM - Tomcat",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "decbytes", "label": "memory" }
   ],
   "targets": [
    {
     "expr": "avg(java_lang_Threading_ThreadCount{instance=\"$server:5556\"})",
     "legendFormat": "threads"
    },
    {
     "expr": "avg(java_lang_Memory_HeapMemoryUsage_used{instance=~\"$server:5556\"})",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "JVM - Taskomatic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "decbytes", "label": "memory" }
   ],
   "targets": [
    {
     "expr": "avg(java_lang_Threading_ThreadCount{instance=\"$server:5557\"})",
     "legendFormat": "threads "
    },
    {
     "expr": "avg(java_lang_Memory_HeapMemoryUsage_used{instance=~\"$server:5557\"})",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "Tomcat Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Catalina_ThreadPool_currentThreadsBusy{name=\"\\\"ajp-nio-0:0:0:0:0:0:0:1-8009\\\"\"}",
     "legendFormat": "busy threads"
    },
    {
     "expr": "Catalina_ThreadPool_currentThreadCount{name=\"\\\"ajp-nio-0:0:0:0:0:0:0:1-8009\\\"\"} - Catalina_ThreadPool_currentThreadsBusy{name=\"\\\"ajp-nio-0:0:0:0:0:0:0:1-8009\\\"\"}",
     "legendFormat": "free threads"
    }
   ]
  },
  {
   "title": "MessageQueue Health",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "Saturation" }
   ],
   "targets": [
    {
     "expr": "message_queue_thread_pool_task_count{job=\"tomcat\"} - message_queue_thread_pool_completed_task_count{job=\"tomcat\"}",
     "legendFormat": "queued tasks"
    },
    {
     "expr": "irate(message_queue_thread_pool_completed_task_count{job=\"tomcat\"}[1m])",
     "legendFormat": "tasks per second"
    }
   ]
  },
  {
   "title": "MessageQueue Utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "message_queue_thread_pool_threads_active{job=\"tomcat\"}",
     "legendFormat": "busy threads"
    },
    {
     "expr": "message_queue_thread_pool_threads{job=\"tomcat\"} - message_queue_thread_pool_threads_active{job=\"tomcat\"}",
     "legendFormat": "free threads"
    }
   ]
  },
  {
   "title": "Database",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short", "label": "operations " }
   ],
   "targets": [
    {
     "expr": "avg(rate(pg_stat_database_tup_fetched{instance=~\"$server:.*\", datname=\"susemanager\"}[5m]))",
     "legendFormat": "fetched"
    },
    {
     "expr": "avg(rate(pg_stat_database_tup_inserted{instance=~\"$server:.*\", datname=\"susemanager\"}[5m]))",
     "legendFormat": "inserted"
    },
    {
     "expr": "avg(rate(pg_stat_database_tup_updated{instance=~\"$server:.*\", datname=\"susemanager\"}[5m]))",
     "legendFormat": "updated"
    },
    {
     "expr": "avg(rate(pg_stat_database_tup_deleted{instance=~\"$server:.*\", datname=\"susemanager\"}[5m]))",
     "legendFormat": "deleted"
    },
    {
     "expr": "sum(pg_locks_count{job=\"suma-server\",datname=\"susemanager\", mode=~\".*exclusive.*\"})",
     "legendFormat": "exclusive"
    },
    {
     "expr": "sum(pg_locks_count{job=\"suma-server\",datname=\"susemanager\", mode!~\".*exclusive.*\"})",
     "legendFormat": "shared"
    }
   ]
  },
  {
   "title": "SUSE Manager actions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short", "label": "actions / sec" }
   ],
   "targets": [
    {
     "expr": "avg(irate(mgr_serveractions_failed{instance=~\"$server:.*\"}[5m]))",
     "legendFormat": "failed"
    },
    {
     "expr": "avg(irate(mgr_serveractions_completed{instance=~\"$server:.*\"}[5m]))",
     "legendFormat": "completed"
    },
    {
     "expr": "avg(mgr_serveractions_queued{instance=~\"$server:.*\"})",
     "legendFormat": "queued"
    },
    {
     "expr": "avg(mgr_serveractions_picked_up{instance=~\"$server:.*\"})",
     "legendFormat": "picked up"
    }
   ]
  },
  {
   "title": "Tasks - Taskomatic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "none", "label": "tasks/sec" }
   ],
   "targets": [
    {
     "expr": "avg (taskomatic_scheduler_threads{instance=~\"$server:9800\"})",
     "legendFormat": "threads total"
    },
    {
     "expr": "avg (taskomatic_scheduler_threads_active{instance=~\"$server:9800\"})",
     "legendFormat": "threads active"
    },
    {
     "expr": "avg(irate(taskomatic_scheduler_completed_task_count{instance=~\"$server:9800\"}[1m]))",
     "legendFormat": "tasks completed"
    }
   ]
  },
  {
   "title": "Locust",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "Simulated Users",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "locust_user_count", "legendFormat": "users" }
     ]
    },
    {
     "title": "Requests Per Second",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(locust_requests_current_rps)",
       "legendFormat": "rps"
      }
     ]
    },
    {
     "title": "Average Response Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "locust_requests_avg_response_time",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "HTTP Failures per second",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(locust_requests_num_failures[5m])",
       "legendFormat": "{{path}}"
      }
     ]
    }
   ]
  }
 ]
}